# -*- coding: utf-8 -*-
"""Project DE .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pBfh5A4PvMV-lDkhqPVc-SXlDJdgy6eJ
"""

# -*- coding: utf-8 -*-
"""DE_GIU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYAihLnV2Y-T-s2xO6sWwAGxapZXFO2v
"""
# ---------------------------------------
### 1. Imports
# ---------------------------------------

import pandas as pd
import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns
import os

from dash import Dash, html, dcc, Input, Output, clientside_callback, callback
import plotly.express as px
import dash_bootstrap_components as dbc
from dash_bootstrap_templates import load_figure_template

# The following notebook-style pip install command is invalid in a plain .py file.
# If you need to install dependencies, run the pip command in your shell or uncomment
# the programmatic installer below.
#
# Example shell command (run in terminal, not in this .py file):
# pip install dash dash-bootstrap-components dash-bootstrap-templates
#
# Optional programmatic installer (uncomment to enable):
# import sys, subprocess
# subprocess.check_call([sys.executable, "-m", "pip", "install", "--quiet",
#                        "dash", "dash-bootstrap-components", "dash-bootstrap-templates"])
#
#print("=> Done installing dash requirements.")







# ---------------------------------------
# Load your integrated dataset
# df_merged must already be prepared
# ---------------------------------------

# Example: You already created df_merged before this script
# Just make sure it exists in memory here

df_merged = pd.read_csv("cleaned_nyc_crashes.csv", low_memory=True, chunksize=100000)

# Filter rows that have valid coordinates (recommended)
df_plot = df_merged[
    ~(df_merged["LATITUDE"].isna() | df_merged["LONGITUDE"].isna())
].copy()

# If injury column exists (adjust if needed)
injury_column = "NUMBER_OF_PERSONS_INJURED"
if injury_column not in df_plot.columns:
    raise ValueError(f"Column '{injury_column}' not found in df_merged!")

load_figure_template(["minty", "minty_dark"])

# ---------------------------------------
### 3. Build Dash App
# ---------------------------------------

app = Dash(__name__, external_stylesheets=[dbc.themes.MINTY, dbc.icons.FONT_AWESOME])

color_mode_switch = html.Span(
    [
        dbc.Label(className="fa fa-moon", html_for="switch"),
        dbc.Switch(id="switch", value=False, className="d-inline-block ms-1", persistence=True),
        dbc.Label(className="fa fa-sun", html_for="switch"),
    ]
)

app.layout = dbc.Container(
    [
        html.Div(["NYC Collision Integrated Data Visualization"],
                  className="bg-primary text-white h3 p-2"),

        color_mode_switch,

        # Dropdown to choose borough (optional)
        dbc.Row([
            dbc.Col(
                dcc.Dropdown(
                    id="borough-filter",
                    options=[{"label": b, "value": b} for b in sorted(df_plot["BOROUGH"].unique())],
                    placeholder="Select Borough (optional)",
                    clearable=True,
                ),
                width=4
            )
        ], className="my-2"),

        dcc.Graph(id="graph", className="border"),
    ]
)

# ---------------------------------------
### 4. Figure Callback
# ---------------------------------------
@callback(
    Output("graph", "figure"),
    Input("switch", "value"),
    Input("borough-filter", "value"),
)
def update_figure_template(switch_on, borough):

    template = "minty" if switch_on else "minty_dark"

    # Filter by borough if selected
    dff = df_plot.copy()
    if borough:
        dff = dff[dff["BOROUGH"] == borough]

    # Build scatter plot of collisions
    fig = px.scatter(
        dff,
        x="LONGITUDE",
        y="LATITUDE",
        size=injury_column,
        color="BOROUGH",
        hover_data=["COLLISION_ID", "PERSON_TYPE", "PERSON_INJURY"],
        template=template,
        size_max=40,
        title="Collision Map by Injury Count",
    )

    fig.update_layout(height=650)

    return fig


# ---------------------------------------
# Client-side Theme Switch
# ---------------------------------------
clientside_callback(
    """
    (switchOn) => {
       switchOn
         ? document.documentElement.setAttribute('data-bs-theme', 'light')
         : document.documentElement.setAttribute('data-bs-theme', 'dark')
       return window.dash_clientside.no_update
    }
    """,
    Output("switch", "id"),
    Input("switch", "value"),
)
# ---------------------------------------
### 5. Run Server
# ---------------------------------------
port = int(os.environ.get("PORT", 8050))

if __name__ == "__main__":
    app.run_server(debug=False, host = "0.0.0.0", port=port)